### ISSUE TITLE
Weather occurrs inside houses

### ISSUE THREAD

**Issue by Bastrabun** [t-affeldt/regional_weather#11]
Those with low ceiling are not affected, but as soon as it's some high ceiling hall, it's raining "through the roof". 

High ceiling means 10m

![image](https://github.com/t-affeldt/regional_weather/assets/59294479/95d4abc1-d5bd-405c-a882-54772e199d16)

Could you please make it that even high buildings with a ceiling of 50+ meters are not rained into? :D

**Comment by Bastrabun** [comment]
Weather also occurs in the ocean:

![image](https://github.com/t-affeldt/regional_weather/assets/59294479/a058d9be-5788-4553-a197-e2daf967d884)

**Comment by DragonWrangler1** [comment]
the issue resides within climate_api.

I made a rather crude fix for these issues here

https://github.com/DragonWrangler1/climate_api

**Comment by t-affeldt** [comment]
Hello! Very late reply as I don't have any time for modding and unfortunately, having to leave this mod mostly abandoned for the time being.

It is a known problem that only arises if your ceiling is more than ten blocks high and either made from transparent nodes (including slabs and stairs) or so high up that it doesn't get rendered.

No code changes are necessary to prevent this behavious. It can already be mitigated with a setting within the Climate API configuration. Look for an option labeled "Check x nodes on outdoor test" (or _ceiling_checks_ in the settingtypes). It is set to ten by default. You can increase the value to detect transparent nodes at a greater range. The default value is admittedly quite low for performance reasons.

I am closing this for now but feel free to reopen if any questions arise.
