### ISSUE TITLE
Weather effect not view from house.

### ISSUE THREAD

**Issue by PikaYellow35** [t-affeldt/regional_weather#2]
Hi. I'm installed and activated this and see that weather effect particles disabling if player in house. I.e. for example start a rain, i`m return in house and see in window. Skybox is right, cloudy, but rain not seen. If exit from house, rain is start again.

Minetest version; 0.5.2.
Climate API - 80d661f33a75f092ddb3c7da4d84daa43a6eda5e
Regional Weather - 920f80e044f7035fc18b603cbc174583384859c3

**Comment by t-affeldt** [comment]
Yes. This is a known issue and unfortunately there is no good way of fixing it.
As is the issue with all weather mods right now, you will either get rain particles inside(meaning that it'll rain even underneath a roof) or no particles at all when indoors. So sadly this is not going to get fixed any time soon.
