### ISSUE TITLE
Mod Conflicts

### ISSUE THREAD

**Issue by IFRFSX** [t-affeldt/regional_weather#3]
This mod conflicts with another mod (https://github.com/BrunoMine/sprint).
When two mods are activated at the same time, the acceleration effect of Sprint Mod (press the Special Key) is completely ineffective.
Do you Repair this problem?

**Comment by t-affeldt** [comment]
Hello. Thank you for your report.

This is unfortunately a problem with the mentioned sprint mod, not regional weather.
Mods that interact with player physics are likely to conflict with each other unless both mods implement an additional API layer like player_monoids. This sprint mod makes no such attempt to prevent issues.

You can however use regional weather with other sprint mods as long as they support either  player_monoids, playerphysics or pova. My personal recommandation is [hbsprint](https://github.com/minetest-mods/hbsprint) for which I can guarantee it is working. It is also very customizable. Make sure to also install [player_monoids](https://github.com/minetest-mods/player_monoids) (from Github, not ContentDB) to make them compatible.
I have tested even more sprint mods from ContentDB that all worked but I prefer hbsprint. Just look out for their optional dependencies. If that includes one of the three API layers then you shouldn't run into issues.

If you really want this specific sprint mod to work then you will need to inform the respective mod author about the issue.
