### ISSUE TITLE
[Bug] player_monoids incompatibility

### ISSUE THREAD

**Issue by happy-sadan** [t-affeldt/regional_weather#5]
It seems using `player_monoids` with `regional_weather` disables all movement except jumping.

**Comment by t-affeldt** [comment]
Which version of player_monoids are you using? The one on ContentDB had a bug, last time I checked it. So you have to use the latest version on Github: https://github.com/minetest-mods/player_monoids

**Comment by happy-sadan** [comment]
Indeed, the master branch seems to fix this issue. Is anything stopping this bug fix from being released as 1.0.1 ?

**Comment by t-affeldt** [comment]
There's sadly nothing I can do about this. It's not an incompatibility that I could fix on my end. The version on ContentDB is straight up broken. So you might run into similar issues using other mods that use it. The only way to resolve this issue is to use the fixed version on Github.

**Comment by happy-sadan** [comment]
Why exactly can't this bug fix be released on ContentDB ?

**Comment by t-affeldt** [comment]
It absolutely can. It would just need to be released by whoever maintains the player_monoids mod, ideally. Feel free to open an issue on their Github.

**Comment by happy-sadan** [comment]
Right, I mixed up the two and forgot that the issue was from `player_monoids`. Thanks for your help, and even though I haven't experienced it thoroughly yet, thanks for this amazing mod !

PS: I think this issue, for now, should be mentioned in README.md and on ContentDB, although I'd understand you wouldn't consider this to be your duty.
