### ISSUE TITLE
Player speed modifications affect underground players

### ISSUE THREAD

**Issue by ainola** [t-affeldt/regional_weather#7]
Thanks for making this great mod!

I've ended up turning regional_weather_player_speed to false because of unexpected movement behaviors when underground, safely away from the weather.

If there's a technical limitation to this, perhaps setting a "lowest height for effect" setting would be useful?

**Comment by t-affeldt** [comment]
Sorry for my very late reply. The setting you are looking for does indeed exist. It's called regional_weather_min_height and can be found under Advanced Settings -> Regional Weather -> World Configuration -> Minimum height of weather effects.

**Comment by t-affeldt** [comment]
I also just pushed an update. The effect now shouldn't happen anymore while underground or indoors, even with default settings and speed modifiers enabled.
